---
title: "Data Preprocessing"
author: "Zexuan Zhao"
date: "2022-12-01"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mltools)
library(data.table)
library(tidyverse)
```

```{r message=FALSE}
raw_data <- read_csv("AppendixS1.csv") 
```

```{r}
plot_multi_histogram <- function(df, feature, label_column) {
    plt <- ggplot(df, aes(x=eval(parse(text=feature)), fill=eval(parse(text=label_column)))) +
    #geom_histogram(alpha=0.7, position="identity", aes(y = ..density..), color="black") +
    geom_density(alpha=0.7) +
    geom_vline(aes(xintercept=mean(eval(parse(text=feature)))), color="black", linetype="dashed", size=1) +
    labs(x=feature, y = "Density")
    plt + guides(fill=guide_legend(title=label_column))
}

plot_multi_histogram(raw_data %>% filter(n < 10) %>% mutate(n = as.character(n)), 'dgp', 'n')
plot_multi_histogram(raw_data %>% filter(n < 10) %>% mutate(n = as.character(n)), 'dep', 'n')
```


```{r}
data <- raw_data %>% 
  filter(n >= 6) %>% 
  select(-Species, -Genus, -Family, -Order, -Class, -Phylum, -Kingdom) %>% 
  select(-Gene) %>% 
  select(-r, -c, -t, -p,	-f,	-fp,	-cgeo,	-tgeo,	-pgeo,	-cenv,	-tenv,	-penv) %>% 
  select(-pmtr, -dgr, -der, -ger, -bp, -pi) %>% 
  select(-pmtp, -gep) %>% 
  na.omit() 
```

```{r}
metabolism_habit <- data %>% 
  select(Metabolism, Habit) %>% 
  mutate(Metabolism = as.factor(Metabolism),
         Habit = as.factor(Habit)) %>% 
  as.data.table()

metabolism_habit_hot_encoded <- one_hot(metabolism_habit) %>% 
  as_tibble()

data_hot_encoded <- data %>% 
  select(-Metabolism, -Habit) %>% 
  bind_cols(metabolism_habit_hot_encoded)
```

```{r}
X <- data_hot_encoded %>% 
  select(-dgp, -dep) %>% 
  scale() %>% 
  as_tibble()
Y <- data_hot_encoded %>% 
  select(dgp, dep)
```

```{r}
write_csv(X, "X.csv")
write_csv(Y, "Y.csv")
```

