---
title: "Neural Network"
author: "Zexuan Zhao"
date: "2022-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mltools)
library(data.table)
library(neuralnet)
library(tidyverse)
```

Prepare data

```{r}
data <- read_csv("AppendixS1.csv") %>% 
#  filter(Class == "Mammalia") %>% 
  select(-Species, -Genus, -Family, -Order, -Class, -Phylum, -Kingdom) %>% 
  select(-Gene) %>% 
  select(-r, -c, -t, -p,	-f,	-fp,	-cgeo,	-tgeo,	-pgeo,	-cenv,	-tenv,	-penv) %>% 
  select(-pmtr, -dgr, -der, -ger, -bp, -pi) %>% 
  select(-pmtp, -gep) %>% 
  na.omit() %>% 
  filter(n > 10) %>% 
  mutate(#pmtp = p.adjust(pmtp, method = "BH"),
         dgp_bh = p.adjust(dgp, method = "BH"),
         dep_bh = p.adjust(dep, method = "BH"))

metabolism_habit <- data %>% 
  select(Metabolism, Habit) %>% 
  mutate(Metabolism = as.factor(Metabolism),
         Habit = as.factor(Habit)) %>% 
  as.data.table()

metabolism_habit_hot_encoded <- one_hot(metabolism_habit) %>% 
  as_tibble()

data_hot_encoded <- data %>% 
  select(-Metabolism, -Habit) %>% 
  bind_cols(metabolism_habit_hot_encoded)

data %>% 
  mutate(dgp_p = dgp > 0.05, dgp_bh_p = dgp_bh > 0.05) %>% 
  group_by(dgp_p, dgp_bh_p) %>% 
  summarize(n = n())
```

```{r}
sig_level <- 0.05
Y <- data_hot_encoded %>% 
  #mutate(pmtp = ifelse(pmtp > sig_level, FALSE, TRUE) ) %>% 
  mutate(dgp = ifelse(dgp > sig_level, FALSE, TRUE) %>% as.numeric()) %>% 
  mutate(dep = ifelse(dep > sig_level, FALSE, TRUE) %>% as.numeric()) %>% 
  select(dgp, dep)
X <- data_hot_encoded %>% 
  select(-dgp, -dep)
```


```{r}
balancing_sample <- function(data){
  N = nrow(data)
  data_dgpp_depp <- data %>% 
    filter(dgp == 1 & dep == 1)
  data_dgpp_depn <- data %>% 
    filter(dgp == 1 & dep == 0)
  data_dgpn_depp <- data %>% 
    filter(dgp == 0 & dep == 1)
  data_dgpn_depn <- data %>% 
    filter(dgp == 0 & dep == 0)
  new_data <- data_dgpp_depp[sample(x = 1:nrow(data_dgpp_depp), size = N, replace = TRUE), ] %>% 
    bind_rows(data_dgpp_depn[sample(x = 1:nrow(data_dgpp_depn), size = N, replace = TRUE), ]) %>% 
    bind_rows(data_dgpn_depp[sample(x = 1:nrow(data_dgpn_depp), size = N, replace = TRUE), ]) %>% 
    bind_rows(data_dgpn_depn[sample(x = 1:nrow(data_dgpn_depn), size = N, replace = TRUE), ])
  new_data[sample(x = 1:nrow(new_data), size = nrow(new_data), replace = FALSE), ]
}
```

```{r}
data_balanced <- X %>% 
  scale() %>% 
  bind_cols(Y) %>% 
  balancing_sample()
n <- neuralnet(dgp + dep ~ .,
               data = data_balanced,
               hidden = c(36, 24, 12),
               err.fct = "ce",
               linear.output = F,
               lifesign = 'full',
               rep=1)
```

```{r}
pred <- predict(n, data_balanced) %>% 
  as_tibble()
names(pred) <- c("pre_dgp", "pre_dep")
true <- data_balanced %>% 
  select(dgp, dep)
```


```{r}
pred %>% 
  group_by(dgp, dep) %>% 
  summarize(n = n())
true %>% 
  group_by(dgp, dep) %>% 
  summarize(n = n())
```

